/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Hospital } from "./Hospital";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Hospital__factory } from "./factories/Hospital__factory";
export { Lock__factory } from "./factories/Lock__factory";
